# error test
GET http://localhost:8080/error
Content-Type: application/json

###

# get all books
GET http://localhost:8080/books
Content-Type: application/json

###

# add book
POST http://localhost:8080/books
Content-Type: application/json

{"isbn":"9780007525546","name":"반지의 제왕","author":"J. R. R. 톨킨","createdAt":"2018-10-26T08:05:57+00:00"}

###

